# Generated by Django 5.1 on 2024-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer1',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer2',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer3',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer4',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
