# Generated by Django 5.1 on 2024-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_answer1_alter_test_answer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
